extend type Mutation {
  """
  ✨ Insert a single `Achievement` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  achievement_insert(
    """
    Data object to insert into the table.
    """
    data: Achievement_Data!
  ): Achievement_KeyOutput! @fdc_generated(from: "Achievement", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PersonalRecord` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  personalRecord_insert(
    """
    Data object to insert into the table.
    """
    data: PersonalRecord_Data!
  ): PersonalRecord_KeyOutput! @fdc_generated(from: "PersonalRecord", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Session` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  session_insert(
    """
    Data object to insert into the table.
    """
    data: Session_Data!
  ): Session_KeyOutput! @fdc_generated(from: "Session", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Set` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  set_insert(
    """
    Data object to insert into the table.
    """
    data: Set_Data!
  ): Set_KeyOutput! @fdc_generated(from: "Set", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Streak` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  streak_insert(
    """
    Data object to insert into the table.
    """
    data: Streak_Data!
  ): Streak_KeyOutput! @fdc_generated(from: "Streak", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserAchievement` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userAchievement_insert(
    """
    Data object to insert into the table.
    """
    data: UserAchievement_Data!
  ): UserAchievement_KeyOutput! @fdc_generated(from: "UserAchievement", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Workout` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workout_insert(
    """
    Data object to insert into the table.
    """
    data: Workout_Data!
  ): Workout_KeyOutput! @fdc_generated(from: "Workout", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WorkoutExercise` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workoutExercise_insert(
    """
    Data object to insert into the table.
    """
    data: WorkoutExercise_Data!
  ): WorkoutExercise_KeyOutput! @fdc_generated(from: "WorkoutExercise", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Achievement` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  achievement_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Achievement_Data!]!
  ): [Achievement_KeyOutput!]! @fdc_generated(from: "Achievement", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PersonalRecord` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  personalRecord_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PersonalRecord_Data!]!
  ): [PersonalRecord_KeyOutput!]! @fdc_generated(from: "PersonalRecord", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Session` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  session_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Session_Data!]!
  ): [Session_KeyOutput!]! @fdc_generated(from: "Session", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Set` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  set_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Set_Data!]!
  ): [Set_KeyOutput!]! @fdc_generated(from: "Set", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Streak` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  streak_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Streak_Data!]!
  ): [Streak_KeyOutput!]! @fdc_generated(from: "Streak", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserAchievement` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userAchievement_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserAchievement_Data!]!
  ): [UserAchievement_KeyOutput!]! @fdc_generated(from: "UserAchievement", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Workout` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workout_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Workout_Data!]!
  ): [Workout_KeyOutput!]! @fdc_generated(from: "Workout", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WorkoutExercise` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workoutExercise_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WorkoutExercise_Data!]!
  ): [WorkoutExercise_KeyOutput!]! @fdc_generated(from: "WorkoutExercise", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Achievement` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Achievement`.
  """
  achievement_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Achievement_Data!
  ): Achievement_KeyOutput! @fdc_generated(from: "Achievement", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PersonalRecord` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PersonalRecord`.
  """
  personalRecord_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PersonalRecord_Data!
  ): PersonalRecord_KeyOutput! @fdc_generated(from: "PersonalRecord", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Session` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Session`.
  """
  session_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Session_Data!
  ): Session_KeyOutput! @fdc_generated(from: "Session", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Set` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Set`.
  """
  set_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Set_Data!
  ): Set_KeyOutput! @fdc_generated(from: "Set", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Streak` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Streak`.
  """
  streak_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Streak_Data!
  ): Streak_KeyOutput! @fdc_generated(from: "Streak", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserAchievement` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserAchievement`.
  """
  userAchievement_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserAchievement_Data!
  ): UserAchievement_KeyOutput! @fdc_generated(from: "UserAchievement", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Workout` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Workout`.
  """
  workout_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Workout_Data!
  ): Workout_KeyOutput! @fdc_generated(from: "Workout", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WorkoutExercise` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkoutExercise`.
  """
  workoutExercise_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WorkoutExercise_Data!
  ): WorkoutExercise_KeyOutput! @fdc_generated(from: "WorkoutExercise", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Achievement` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Achievement`.
  """
  achievement_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Achievement_Data!]!
  ): [Achievement_KeyOutput!]! @fdc_generated(from: "Achievement", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PersonalRecord` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PersonalRecord`.
  """
  personalRecord_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PersonalRecord_Data!]!
  ): [PersonalRecord_KeyOutput!]! @fdc_generated(from: "PersonalRecord", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Session` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Session`.
  """
  session_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Session_Data!]!
  ): [Session_KeyOutput!]! @fdc_generated(from: "Session", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Set` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Set`.
  """
  set_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Set_Data!]!
  ): [Set_KeyOutput!]! @fdc_generated(from: "Set", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Streak` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Streak`.
  """
  streak_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Streak_Data!]!
  ): [Streak_KeyOutput!]! @fdc_generated(from: "Streak", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserAchievement` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserAchievement`.
  """
  userAchievement_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserAchievement_Data!]!
  ): [UserAchievement_KeyOutput!]! @fdc_generated(from: "UserAchievement", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Workout` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Workout`.
  """
  workout_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Workout_Data!]!
  ): [Workout_KeyOutput!]! @fdc_generated(from: "Workout", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WorkoutExercise` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkoutExercise`.
  """
  workoutExercise_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WorkoutExercise_Data!]!
  ): [WorkoutExercise_KeyOutput!]! @fdc_generated(from: "WorkoutExercise", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Achievement` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Achievement` or `null` if not found.
  """
  achievement_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Achievement_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Achievement_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Achievement_Data!
  ): Achievement_KeyOutput @fdc_generated(from: "Achievement", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PersonalRecord` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PersonalRecord` or `null` if not found.
  """
  personalRecord_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PersonalRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonalRecord_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PersonalRecord_Data!
  ): PersonalRecord_KeyOutput @fdc_generated(from: "PersonalRecord", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Session` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Session` or `null` if not found.
  """
  session_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Session_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Session_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Session_Data!
  ): Session_KeyOutput @fdc_generated(from: "Session", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Set` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Set` or `null` if not found.
  """
  set_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Set_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Set_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Set_Data!
  ): Set_KeyOutput @fdc_generated(from: "Set", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Streak` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Streak` or `null` if not found.
  """
  streak_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Streak_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Streak_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Streak_Data!
  ): Streak_KeyOutput @fdc_generated(from: "Streak", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserAchievement` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserAchievement` or `null` if not found.
  """
  userAchievement_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserAchievement_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserAchievement_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserAchievement_Data!
  ): UserAchievement_KeyOutput @fdc_generated(from: "UserAchievement", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Workout` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Workout` or `null` if not found.
  """
  workout_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Workout_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Workout_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Workout_Data!
  ): Workout_KeyOutput @fdc_generated(from: "Workout", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WorkoutExercise` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WorkoutExercise` or `null` if not found.
  """
  workoutExercise_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkoutExercise_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkoutExercise_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WorkoutExercise_Data!
  ): WorkoutExercise_KeyOutput @fdc_generated(from: "WorkoutExercise", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Achievement` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  achievement_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Achievement_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Achievement_Data!
  ): Int! @fdc_generated(from: "Achievement", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PersonalRecord` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  personalRecord_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PersonalRecord_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PersonalRecord_Data!
  ): Int! @fdc_generated(from: "PersonalRecord", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Session` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  session_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Session_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Session_Data!
  ): Int! @fdc_generated(from: "Session", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Set` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  set_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Set_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Set_Data!
  ): Int! @fdc_generated(from: "Set", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Streak` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  streak_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Streak_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Streak_Data!
  ): Int! @fdc_generated(from: "Streak", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserAchievement` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userAchievement_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserAchievement_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserAchievement_Data!
  ): Int! @fdc_generated(from: "UserAchievement", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Workout` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  workout_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Workout_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Workout_Data!
  ): Int! @fdc_generated(from: "Workout", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WorkoutExercise` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  workoutExercise_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WorkoutExercise_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WorkoutExercise_Data!
  ): Int! @fdc_generated(from: "WorkoutExercise", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Achievement` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  achievement_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Achievement_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Achievement_FirstRow
  ): Achievement_KeyOutput @fdc_generated(from: "Achievement", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PersonalRecord` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  personalRecord_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PersonalRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonalRecord_FirstRow
  ): PersonalRecord_KeyOutput @fdc_generated(from: "PersonalRecord", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Session` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  session_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Session_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Session_FirstRow
  ): Session_KeyOutput @fdc_generated(from: "Session", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Set` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  set_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Set_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Set_FirstRow
  ): Set_KeyOutput @fdc_generated(from: "Set", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Streak` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  streak_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Streak_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Streak_FirstRow
  ): Streak_KeyOutput @fdc_generated(from: "Streak", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserAchievement` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userAchievement_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: UserAchievement_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserAchievement_FirstRow
  ): UserAchievement_KeyOutput @fdc_generated(from: "UserAchievement", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Workout` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  workout_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Workout_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Workout_FirstRow
  ): Workout_KeyOutput @fdc_generated(from: "Workout", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WorkoutExercise` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  workoutExercise_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkoutExercise_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkoutExercise_FirstRow
  ): WorkoutExercise_KeyOutput @fdc_generated(from: "WorkoutExercise", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Achievement` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  achievement_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Achievement_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Achievement", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PersonalRecord` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  personalRecord_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PersonalRecord_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PersonalRecord", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Session` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  session_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Session_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Session", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Set` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  set_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Set_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Set", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Streak` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  streak_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Streak_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Streak", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserAchievement` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userAchievement_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserAchievement_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserAchievement", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Workout` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  workout_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Workout_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Workout", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WorkoutExercise` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  workoutExercise_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WorkoutExercise_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WorkoutExercise", purpose: DELETE_MULTIPLE)
}
